import glob

####
# import the environment
####
Import('env build_dir TOOLPATH')
env = env.Clone()
env.Tool("opencv",toolpath=TOOLPATH)
env.Append(CPPPATH=build_dir)

####
# build sources
####
srcs = map(lambda x,bd=build_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
srcs = env.Moc(env.Uic("%s/RxDialog.ui" % build_dir)) + srcs
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to ease building it later
####
lib = env.SharedLibrary('%s/Rx' % build_dir,objs)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('Rx', libInstall)

####
# return the plug-in library
####
Return("libInstall")
