import glob

####
# import the environment
####
Import('env')
build_dir = '%s/SpectralUtilities' % env["BUILDDIR"]

####
# build sources
####
srcs = map(lambda x,bd=build_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.Object(srcs)

####
# build the plug-in library and set up an alias to wase building it later
####
lib = env.Library('%s/SpectralUtilities' % build_dir,objs)
libinstall = env.Install(env["LIBDIR"], lib)
env.Alias('SpectralUtilities', libinstall)

####
# return the plug-in library
####
Return("libinstall")
